---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: management1
    groups:
      - iceberg1
    image: "quay.io/actatux/ansible-${MOLECULE_DISTRO:-centos:8}"
    override_command: false
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    host_vars:

      management1:
        j2_current_iceberg: iceberg1
        icebergs_system: false
        enable_services: true
        start_services: true
        ep_equipment_type: server

    hosts:
      fake_computes:
        hosts:
          compute1:
            bmc:
              ip4: 10.10.102.1
              mac: 08:00:27:dc:f8:a7
              name: blogin1
              network: ice1-1
            ep_equipment_type: server
            ep_equipment_authentication:
              user: 'ADMIN'
              password: 'ADMIN'
verifier:
  name: ansible
