---

- name: "Template >> /etc/hosts {% if accelerated_mode %} >>>A>C>C>E>L>E>R>A>T>E>D>>> {% endif %}"
  template:
    src: "hosts{% if accelerated_mode %}_accelerated_mode{% endif %}.j2"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - template
