---
- name: Verify
  hosts: management1
  tasks:

    - name: Collect package facts
      package_facts:
        manager: auto

    - name: Collect services facts
      service_facts:

    - name: Collect services of zone public
      command: firewall-cmd --zone=public --list-all
      register: firewall_cmd_result
      changed_when: False

    - name: Firewall zone public check presence of service dhcp
      assert:
        that: firewall_cmd_result.stdout |
                    regex_findall(('dhcp|dhcpv6-client'), multiline=False) | length == 2

    - name: Assert dhcp-server package is installed
      assert:
        that: "'dhcp-server' in ansible_facts.packages"

    - name: Check dhcpd is enabled
      assert:
        that: "ansible_facts.services['dhcpd.service'].status == 'enabled'"

    - name: Check dhcpd is running
      assert:
        that: "ansible_facts.services['dhcpd.service'].state == 'running'"

    # Check all conf files

    - name: Retrieve file dhcpd.conf system status
      stat:
        path: /etc/dhcp/dhcpd.conf
      register: reg_dhcp

    - name: Assert file dhcpd.conf exist
      assert:
        that: reg_dhcp.stat.exists

    - name: Retrieve file dhcpd.ice1-1.conf system status
      stat:
        path: /etc/dhcp/dhcpd.ice1-1.conf
      register: reg_dhcp1

    - name: Assert file dhcpd.ice1-1.conf exist
      assert:
        that: reg_dhcp1.stat.exists

    - name: Retrieve file dhcpd.ice1-2.conf system status
      stat:
        path: /etc/dhcp/dhcpd.ice1-2.conf
      register: reg_dhcp2

    - name: Assert file dhcpd.ice1-2.conf exist
      assert:
        that: reg_dhcp2.stat.exists

    - name: Retrieve file dhcpd.networks.conf system status
      stat:
        path: /etc/dhcp/dhcpd.networks.conf
      register: reg_dhcp_network_file

    - name: Assert file dhcpd.networks.conf exist
      assert:
        that: reg_dhcp_network_file.stat.exists

    - name: Retrieve ignore-client-uids configuration in /etc/dhcp/dhcpd.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.conf
        regexp: "ignore-client-uids False;"
        state: absent
      check_mode: yes
      register: reg_dhcp_uids

    - name: Check /etc/dhcp/dhcpd.conf file contains (ignore-client-uids=False)
      assert:
        that: reg_dhcp_uids.found

    - name: Retrieve shared-network configuration in /etc/dhcp/dhcpd.networks.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.networks.conf
        regexp: "shared-network wolf"
        state: absent
      check_mode: yes
      register: reg_dhcp_shared_network

    - name: Check /etc/dhcp/dhcpd.networks.conf file contains shared-network
      assert:
        that: reg_dhcp_shared_network.found

    - name: Retrieve subnet 10.11.0.0 configuration in /etc/dhcp/dhcpd.networks.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.networks.conf
        regexp: "subnet 10.10.0.0 netmask 255.255.0.0"
        state: absent
      check_mode: yes
      register: reg_dhcp_subnet1

    - name: Check /etc/dhcp/dhcpd.networks.conf file contains subnet 10.11.0.0
      assert:
        that: reg_dhcp_subnet1.found

    - name: Retrieve subnet 10.30.0.0 configuration in /etc/dhcp/dhcpd.networks.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.networks.conf
        regexp: "subnet 10.30.0.0 netmask 255.255.0.0"
        state: absent
      check_mode: yes
      register: reg_dhcp_subnet2

    - name: Check /etc/dhcp/dhcpd.networks.conf file contains subnet 10.30.0.0
      assert:
        that: reg_dhcp_subnet2.found

    # Check compute with mac address

    - name: Retrieve compute1-ice1-1 in /etc/dhcp/dhcpd.ice1-1.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.ice1-1.conf
        regexp: "host compute1-ice1-1"
        state: absent
      check_mode: yes
      register: register_stat_dhcp_file

    - name: Check /etc/dhcp/dhcpd.ice1-1.conf file contains compute1-ice1-1
      assert:
        that: register_stat_dhcp_file.found

    # Check compute with opt82

    - name: Retrieve option_match_compute2 in /etc/dhcp/dhcpd.ice1-1.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.ice1-1.conf
        regexp: "option_match_compute2"
        state: absent
      check_mode: yes
      register: reg_dhcp_file_opt82

    - name: Check /etc/dhcp/dhcpd.ice1-1.conf file contains opt82 configuration for compute2
      assert:
        that: reg_dhcp_file_opt82.found

    - name: Retrieve circuit-id configuration in /etc/dhcp/dhcpd.ice1-1.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.ice1-1.conf
        regexp: "circuit-id = 01:00:17"
        state: absent
      check_mode: yes
      register: reg_dhcp_file_opt82_circuit_id

    - name: Check /etc/dhcp/dhcpd.ice1-1.conf file contains circuit-id configuration for compute2
      assert:
        that: reg_dhcp_file_opt82_circuit_id.found

    - name: Retrieve option_match_compute2-bmc in /etc/dhcp/dhcpd.ice1-1.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.ice1-1.conf
        regexp: "option_match_compute2-bmc"
        state: absent
      check_mode: yes
      register: reg_dhcp_file_opt82_bmc

    - name: Check /etc/dhcp/dhcpd.ice1-1.conf file contains opt82 configuration for bmc in compute2
      assert:
        that: reg_dhcp_file_opt82_bmc.found

    # Check compute with opt61

    - name: Retrieve compute3-ice1-2 in /etc/dhcp/dhcpd.ice1-2.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.ice1-2.conf
        regexp: "host compute3-ice1-2"
        state: absent
      check_mode: yes
      register: reg_dhcp_file_opt61

    - name: Check /etc/dhcp/dhcpd.ice1-2.conf file contains opt61 configuration for compute3-ice1-2
      assert:
        that: reg_dhcp_file_opt61.found

    - name: Retrieve compute3-bmc in /etc/dhcp/dhcpd.ice1-2.conf file
      lineinfile:
        path: /etc/dhcp/dhcpd.ice1-2.conf
        regexp: "host compute3-bmc"
        state: absent
      check_mode: yes
      register: reg_dhcp_file_opt61_bmc

    - name: Check /etc/dhcp/dhcpd.ice1-2.conf file contains opt82 configuration for bmc in compute3-ice1-2
      assert:
        that: reg_dhcp_file_opt61_bmc.found
