---

- name: group █ Add users groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ users_basic.users }}"

- name: user █ Add/remove users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default('') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.name }}"
    groups: "{{ item.groups | default('yes') }}"
    create_home: "{{item.create_home | default('yes') }}"
    update_password: "{{ item.update_password | default('always') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    home: "{{ item.home | default('/home') }}"
    password: "{{ item.password }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default('no') }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default('2048') }}"
    ssh_key_file: "{{ item.ssh_key_file | default('.ssh/id_rsa') }}"
    remove: "{{ item.remove | default('no') }}"
    state: {{ item.state }}
  with_items: "{{ users_basic.users }}"
