external_time:
  time_server:
    server: # List of possible time servers
      - 0.fr.pool.ntp.org
    pool: # List of possible time pools
      - pool.ntp.org
  time_client:
    server:
    pool:

external_dns:
  dns_server: # set as forwarders in named.conf
    - 208.67.222.222
  dns_client: # set directly on client side in resolv.conf
    - 208.67.220.220

# Hosts defined here will be automatically added into /etc/hosts and into DNS configuration
external_hosts:
  sphenisc.com: 213.186.33.3
