---

- name: Set NIC configuration
  template:
    src: ifcfg_opensuse.j2
    dest: /etc/sysconfig/network/ifcfg-{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items: "{{ network_interfaces }}"
  when: network_interfaces[item]['ip4'] is defined and network_interfaces[item]['ip4'] is not none
