---

- name: Setting repositories
  zypper_repository:
    name: "{{ item }}"
    description: "{{ item }} gen by Ansible"
    repo: "http://{{ networks[j2_node_main_network]['services_ip']['repository_ip'] }}/repositories/{{ equipment_profile['operating_system']['repositories_environment'] | default('') }}/{{ equipment_profile['operating_system']['distribution'] }}/{{ equipment_profile['operating_system']['distribution_version'] | default(equipment_profile['operating_system']['distribution_major_version']) }}/{{ equipment_profile['hardware']['cpu']['architecture'] }}/{{ item }}/"
    disable_gpg_check: yes
    state: present
  with_items: "{{ repositories }}"
