---

- name: Setting repositories
  yum_repository:
    name: "{{ item }}"
    description: "{{ item }} gen by Ansible"
    baseurl: "http://{{networks[j2_node_main_network]['services_ip']['repository_ip']}}/repositories/{{equipment_profile['operating_system']['distribution']}}/{{equipment_profile['operating_system']['distribution_version']}}/{{equipment_profile['hardware']['cpu']['architecture']}}/{{item}}"
    gpgcheck: no
  loop: "{{ repositories }}"
  when: item != 'os'

- name: "Setting repositories os ({{ item }})"
  yum_repository:
    name: "{{ item }}"
    description: "{{ item }} gen by Ansible"
    baseurl: "http://{{networks[j2_node_main_network]['services_ip']['repository_ip']}}/repositories/{{equipment_profile['operating_system']['distribution']}}/{{equipment_profile['operating_system']['distribution_version']}}/{{equipment_profile['hardware']['cpu']['architecture']}}/os/{{ item }}"
    gpgcheck: no
  loop:
    - BaseOS
    - AppStream
  when: "'os' in repositories"

- name: "Setting external repository ({{ item }})"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.name }} gen by Ansible"
    baseurl: "{{ item.url }}"
    gpgcheck: no
  loop: "{{ external_repositories | default([]) }}"
