mg_managements:                        # Master group
  children:
    equipment_raspberry_pi_3_arm64:    # Equipment profile
      hosts:
        odin:                          # Hostname
          network_interfaces:
            eth0:
              ip4: 10.10.0.1
              mac: 08:00:27:dc:f8:f5
              network: ice1-1          # Logical network connected to

            
