nfs_settings:
  selinux:
    use_nfs_home_dirs: true                     # Will automatically set this boolean to true if /home is mounted on client side

nfs:

  ansible:
    mount: /etc/bluebanquise
    export: /etc/bluebanquise
    server: management1
    clients_groups:
      - slave_managements
    take_over_network: ice1-1
    export_arguments: ro,no_root_squash,sync
    mount_arguments: ro,intr,nfsvers=4.2,bg

  repositories:
    mount: /var/www/html/repositories
    export: /var/www/html/repositories
    server: management1
    clients_groups:
      - slave_managements
    take_over_network: ice1-1
    export_arguments: ro,no_root_squash,sync
    mount_arguments: ro,intr,rsize=32768,wsize=32768,nfsvers=4.2,bg
