---
- name: Gathering OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/main.yml
  #
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/{{ ansible_facts.os_family }}.yml"
      skip: true

- name: Package
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ slurm_packages_to_install[slurm.slurm_packaging][slurm_profile] }}"

#### MUNGE

- name: File >> /etc/munge/munge.key
  copy:
    src: munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0400

- name: Enable/disable services >> munge
  service:
    name: munge
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  tags:
    - service

- name: Start services >> munge
  service:
    name: munge
    state: started
  when: (start_services | bool)
  tags:
    - service

#### SLURM

- name: Add group >> slurm
  group:
    name: slurm
    gid: 777
    state: present

- name: Add user >> slurm
  user:
    name: slurm
    shell: /bin/false
    uid: 777
    group: slurm
    home: "{{ slurm_home_path }}"
    state: present

- name: Template >> slurm.conf
  template:
    src: slurm.conf.j2
    dest: "{{ slurm_home_path }}/slurm.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - template

- name: File >> /etc/slurm/cgroup.conf
  copy:
    src: cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: root
    group: root
    mode: 0644

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: 0755
  with_items:
    - /var/log/slurm
    - /var/spool/slurmd
    - /var/spool/slurmd/StateSave
    - /var/spool/slurmd/slurmd

- name: Disable slurmctld
  service:
    name: slurmctld
    enabled: no         # Dangerous to enable slurm controller...
  when: slurm_profile == 'controller'

- name: Start services
  service:
    name: slurmctld
    state: started
  when:
    - (start_services | bool)
    - slurm_profile == 'controller'

- name: Enable/disable services
  service:
    name: slurmd
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  when: slurm_profile == 'node'
  tags:
    - service

- name: Start services
  service:
    name: slurmd
    state: started
  when:
    - (start_services | bool)
    - slurm_profile == 'node'
  tags:
    - service
