## Tested on RedHat 8.0

- name: SELinux /var/www/html/preboot_execution_environment/nodes
  sefcontext:
    target: '/var/www/html/preboot_execution_environment/nodes(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  when:
    - ansible_selinux.status == "enabled"

