---

#- name: Use OS dedicated task
#  include_tasks: "{{(ansible_distribution|lower|replace(' ','_'))}}_{{ansible_distribution_major_version}}.yml"

- name: Install minimum packages for PXE
  package:
    name: "{{ packages_to_install[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
    state: present
  tags:
    - package

- name: Create pxe directories structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
   - /var/www/cgi-bin
   - /etc/bluebanquise
   - /etc/bluebanquise/pxe

- name: Create pxe directories structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ apache_user[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
    group: "{{ apache_user[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  loop:
   - /var/www/html/preboot_execution_environment
   - /var/www/html/preboot_execution_environment/bin
   - /var/www/html/preboot_execution_environment/nodes
   - /var/www/html/preboot_execution_environment/equipment_os_configurations
   - /var/www/html/preboot_execution_environment/equipment_ipxe_configurations

- name: Configure access on directory /var/www/html/preboot_execution_environment"
  file:
    path: /var/www/html/preboot_execution_environment
    state: directory
    mode: 0755
    owner: "{{ apache_user[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
    group: "{{ apache_user[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
    recurse: yes

- name: Use OS dedicated task
  include_tasks: "{{(ansible_distribution|lower|replace(' ','_'))}}_{{ansible_distribution_major_version}}.yml"

- name: Templates >> nodes parameters
  template:
    src: nodes_parameters.yml.j2
    dest: /etc/bluebanquise/pxe/nodes_parameters.yml
    mode: 0644
  tags:
    - template

- name: Templates >> menu and convergence
  template:
    src: "{{item}}.ipxe.j2"
    dest: "/var/www/html/preboot_execution_environment/{{item}}.ipxe"
    mode: 0755
  loop:
    - convergence
    - menu
  tags:
    - template

- name: Templates >> nohostname
  template:
    src: nohostname.ipxe.j2
    dest: /var/www/html/preboot_execution_environment/nodes/.ipxe
    mode: 0755
  tags:
    - template

##### Centos

- name: Templates >> kickstarts for Centos
  template:
    src: "kickstart.cfg.j2"
    dest: /var/www/html/preboot_execution_environment/equipment_os_configurations/kickstart.{{item | replace(equipment_naming,'') | trim}}.cfg
    mode: 0644
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) in ['redhat','centos']
  tags:
    - template

- name: Templates >> equipment_ipxe_configurations for Centos
  template:
    src: configuration_centos.ipxe.j2
    dest: /var/www/html/preboot_execution_environment/equipment_ipxe_configurations/{{item | replace(equipment_naming,'') | trim}}.ipxe
    mode: 0644
  with_items: "{{j2_equipment_groups_list}}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) in ['redhat','centos']
  tags:
    - template

##### Ubuntu

- name: Templates >> preseeds for Ubuntu
  template:
    src: "preseed.cfg.j2"
    dest: /var/www/html/preboot_execution_environment/equipment_os_configurations/preseed.{{item | replace(equipment_naming,'') | trim}}.cfg
    mode: 0644
  with_items: "{{j2_equipment_groups_list}}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'ubuntu'
  tags:
    - template

- name: Templates >> equipment_ipxe_configurations for Ubuntu
  template:
    src: "configuration_ubuntu.ipxe.j2"
    dest: /var/www/html/preboot_execution_environment/equipment_ipxe_configurations/{{item | replace(equipment_naming,'') | trim}}.ipxe
    mode: 0644
  with_items: "{{j2_equipment_groups_list}}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'ubuntu'
  tags:
    - template

##### OpenSuse

- name: Templates >> autoyasts for OpenSuse
  template:
    src: "autoyast.xml.j2"
    dest: /var/www/html/preboot_execution_environment/equipment_os_configurations/autoyast.{{item | replace(equipment_naming,'') | trim}}.xml
    mode: 0644
  with_items: "{{j2_equipment_groups_list}}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'opensuse'
  tags:
    - template

- name: Templates >> equipment_ipxe_configurations for OpenSuse
  template:
    src: "configuration_opensuse.ipxe.j2"
    dest: /var/www/html/preboot_execution_environment/equipment_ipxe_configurations/{{item | replace(equipment_naming,'') | trim}}.ipxe
    mode: 0644
  with_items: "{{j2_equipment_groups_list}}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'opensuse'
  tags:
    - template

##### Minimal, specific

- name: Templates >> equipment_ipxe_configuration for Minimal Live Linux
  template:
    src: "configuration_minimal.ipxe.j2"
    dest: /var/www/html/preboot_execution_environment/equipment_ipxe_configurations/minimal.ipxe
    mode: 0644
  tags:
    - template

##### END

- name: bootset tool
  template:
    src: bootset.py.j2
    dest: /usr/bin/bootset
    mode: 0700 
  tags:
    - template

- name: httpd cgi module
  apache2_module:
    state: present
    name: "{{apache_cgi_module[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version]}}"
  notify: Restart pxe services

- name: cgi configuration file
  copy:
    src: cgi.conf
    dest: "{{apache_conf_path[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version]}}/cgi.conf"
    mode: 0644
  notify: Restart pxe services

- name: cgi script
  copy:
    src: bootswitch.cgi
    dest: /var/www/cgi-bin/bootswitch.cgi
    mode: 0744
    owner: "{{apache_user[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version]}}"
    group: "{{apache_user[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version]}}"

- meta: flush_handlers
- name: Start services
  service:
    name: "{{ item }}"
    state: started
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  loop: "{{ services_to_start[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  tags:
    - service
