---
- name: Gathering OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/main.yml
  #
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/{{ ansible_facts.os_family }}.yml"
      skip: true

- name: Install minimum packages for PXE
  package:
    name: "{{ pxe_stack_packages_to_install }}"
    state: present
  tags:
    - package

- name: Create pxe directories structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
   - "{{ pxe_stack_apache_cgi_path }}"
   - /etc/bluebanquise
   - /etc/bluebanquise/pxe

- name: Create pxe directories structure
  file:
    path: "{{ pxe_stack_apache_html_path }}{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  loop:
   - /preboot_execution_environment
   - /preboot_execution_environment/bin
   - /preboot_execution_environment/nodes
   - /preboot_execution_environment/equipment_profiles
   - /preboot_execution_environment/osdeploy

- name: Use OS dedicated task
  include_tasks: "{{ (ansible_facts.distribution|replace(' ','_')) }}_{{ ansible_facts.distribution_major_version }}.yml"

- name: Templates >> nodes parameters
  template:
    src: nodes_parameters.yml.j2
    dest: /etc/bluebanquise/pxe/nodes_parameters.yml
    mode: 0644
  tags:
    - template

- name: Templates >> pxe parameters
  template:
    src: "pxe_parameters.yml.j2"
    dest: "/etc/bluebanquise/pxe/pxe_parameters.yml"
    mode: 0644

- name: Templates >> menu and convergence
  template:
    src: "{{ item }}.ipxe.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/{{ item }}.ipxe"
    mode: 0755
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  loop:
    - convergence
    - menu
  tags:
    - template

- name: Templates >> nohostname
  template:
    src: nohostname.ipxe.j2
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/nodes/.ipxe"
    mode: 0755
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  tags:
    - template

##### Centos

- name: osdeploy files (redhat)
  copy:
    src: osdeploy/redhat_{{ item }}.ipxe
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/osdeploy/redhat_{{ item }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ pxe_stack_supported_os.redhat }}"

- name: osdeploy files (centos)
  copy:
    src: osdeploy/centos_{{ item }}.ipxe
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/osdeploy/centos_{{ item }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ pxe_stack_supported_os.centos }}"

- name: Templates >> kickstarts for Centos
  template:
    src: "kickstart.cfg.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.kickstart.cfg"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) in ['redhat','centos']
  tags:
    - template

- name: Templates >> equipment_profiles for Centos
  template:
    src: "equipment_profile.ipxe.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ j2_equipment_groups_list }}"
  vars:
    distribution: "{{(hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower)}}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) in ['redhat','centos']
  tags:
    - template

##### Ubuntu

- name: Templates >> preseeds for Ubuntu
  template:
    src: "preseed.cfg.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.preseed.cfg"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'ubuntu'
  tags:
    - template

- name: Templates >> equipment_profiles for Ubuntu
  template:
    src: "configuration_ubuntu.ipxe.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'ubuntu'
  tags:
    - template

##### OpenSuse

- name: osdeploy files (opensuse leap)
  copy:
    src: "osdeploy/opensuse_{{ item }}.ipxe"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/osdeploy/opensuse_{{ item }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ pxe_stack_supported_os.opensuse }}"

- name: Templates >> autoyasts for OpenSuse
  template:
    src: "autoyast.xml.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.autoyast.xml"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'opensuse'
  tags:
    - template

- name: Templates >> equipment_profiles for OpenSuse
  template:
    src: "equipment_profile.ipxe.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/equipment_profiles/{{ item | replace(equipment_naming+'_','') | trim }}.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  vars:
    distribution: opensuse
  with_items: "{{ j2_equipment_groups_list }}"
  when:
    - hostvars[groups[item][0]]['equipment_profile']['equipment_type'] == 'server'
    - (hostvars[groups[item][0]]['equipment_profile']['operating_system']['distribution']|lower) == 'opensuse'
  tags:
    - template


##### Minimal, specific

- name: Templates >> equipment_ipxe_configuration for Minimal Live Linux
  template:
    src: "configuration_minimal.ipxe.j2"
    dest: "{{ pxe_stack_apache_html_path }}/preboot_execution_environment/equipment_profiles/minimal.ipxe"
    mode: 0644
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"
  tags:
    - template

##### END

- name: bootset tool
  copy:
    src: bootset.py
    dest: /usr/bin/bootset
    mode: 0700
  tags:
    - template

- name: httpd cgi module
  apache2_module:
    state: present
    name: "{{ pxe_stack_apache_cgi_module }}"
  notify: Restart pxe services

- name: cgi configuration file
  copy:
    src: cgi.conf
    dest: "{{ pxe_stack_apache_conf_path }}/cgi.conf"
    mode: 0644
  notify: Restart pxe services

- name: cgi script
  copy:
    src: bootswitch.cgi
    dest: "{{ pxe_stack_apache_cgi_path }}/bootswitch.cgi"
    mode: 0744
    owner: "{{ pxe_stack_apache_user }}"
    group: "{{ pxe_stack_apache_user }}"

- meta: flush_handlers

- name: Manage services state
  service:
    name: "{{ item }}"
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  loop: "{{ pxe_stack_services_to_start }}"
  tags:
    - service
