## Tested on Centos 7.6

- name: SELinux /var/www/html/preboot_execution_environment/nodes
  sefcontext:
    target: '/var/www/html/preboot_execution_environment/nodes(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present
  when:
    - ansible_facts.selinux.status == "enabled"

