---
pxe_stack_apache_cgi_module: cgid
pxe_stack_apache_conf_path: /etc/httpd/conf.d
pxe_stack_apache_user: apache
pxe_stack_packages_to_install:
  - fbtftp_server
  - ipxe-x86_64-bluebanquise
  - ipxe-arm64-bluebanquise
  - httpd
  - python3-policycoreutils
  - clustershell
  - python3-clustershell
  - policycoreutils
pxe_stack_services_to_start:
  - fbtftp_server
  - httpd
pxe_stack_firewall_services_to_add:
  - http
  - tftp
