---
role_version: 1.0.2

packages_to_install:
  opensuse_leap:
    _15:
      - chrony
  ubuntu:
    _18:
      - chrony
      - tzdata
  redhat:
    _7:
      - chrony
    _8:
      - chrony
  centos:
    _7:
      - chrony
    _8:
      - chrony

services_to_start:
  opensuse_leap:
    _15:
      - chronyd
  ubuntu:
    _18:
      - chronyd
  redhat:
    _7:
      - chronyd
    _8:
      - chronyd
  centos:
    _7:
      - chronyd
    _8:
      - chronyd

chrony_conf_path:
  opensuse_leap:
    _15: /etc/chrony.conf
  ubuntu:
    _18: /etc/chrony/chrony.conf
  redhat:
    _7: /etc/chrony.conf
    _8: /etc/chrony.conf
  centos:
    _7: /etc/chrony.conf
    _8: /etc/chrony.conf
