---
- name: Install conman and ipmitool
  package:
    name:
      - conman
      - ipmitool
    state: present
  tags:
    - package

- name: Template >> /etc/conman.conf
  template:
    src: conman.conf.j2
    dest: /etc/conman.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart conman
  tags:
    - template

- name: Start services
  service:
    name: conman
    state: started
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  tags:
    - service
