---
- name: Install conman and ipmitool
  package:
    name:
      - conman
      - ipmitool
    state: present
  tags:
    - package

- name: Template >> /etc/conman.conf
  template:
    src: conman.conf.j2
    dest: /etc/conman.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart conman
  tags:
    - template

- meta: flush_handlers

- name: Manage services state
  service:
    name: conman
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
    state: "{{ (start_services | bool) | ternary('started', omit) }}"
  tags:
    - service
