---

- name: Package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - opensm
    - opensm-libs

- name: Enable/disable services
  service:
    name: opensm
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  tags:
    - service

- name: Start services
  service:
    name: opensm
    state: started
  when: (start_services | bool)
  tags:
    - service
