---
- name: Prepare
  hosts: molecule_platform

  tasks:
    - name: "update cache apt"
      apt: update_cache=yes
      when: ansible_facts.os_family == "Debian"

    - name: "Ensure /root/.ssh exists"
      file:
        path: "/root/.ssh"
        state: directory
        owner: root
        group: root
        mode: 700
