### General settings file

# Localisation
time_zone: Europe/Brussels

# Internal mechanisms
icebergs_system: false # Activate or deactivate icebergs topology system. Experimental.
accelerated_mode: false # Activate or deactivate accelerated mode. Experimental.

# /etc/hosts
hosts_file:
  range: all # can be all (all hosts) or iceberg (iceberg only)
