---

- name: Ansible CMDB
  package:
    name: "ansible-cmdb"
    state: present
  when: report_settings.enable_ansible_cmdb == true

- name: Create report directories structure
  file:
   path: "{{item}}"
   state: directory
   mode: 0755
  with_items:
   - /var/www/html/report/
   - /var/www/html/report/pictures
   - /var/www/html/report/css
   - /var/www/html/report/inventory_checker
   - /var/www/html/report/graphs

- name: Template >> /var/www/html/report/index.html
  template:
    src: "index.html.j2"
    dest: /var/www/html/report/index.html
    owner: root
    group: root
    mode: 0644
  tags:
    - templates

- name: Template >> /var/www/html/report/css/main.css
  template:
    src: "main.css.j2"
    dest: /var/www/html/report/css/main.css
    owner: root
    group: root
    mode: 0644
  tags:
    - templates

- name: Copy >> bluebanquise logo white
  copy:
    src: bluebanquise_logo_white.svg
    dest: /var/www/html/report/pictures/bluebanquise_logo_white.svg
    mode: 0644

- name: Template >> /var/www/html/report/inventory_checker.html
  template:
    src: "inventory_checker.html.j2"
    dest: /var/www/html/report/inventory_checker.html
    owner: root
    group: root
    mode: 0644
  tags:
    - templates
  when:
    - report_settings.inventory_checker is defined
    - report_settings.inventory_checker is not none
    - report_settings.inventory_checker
    - report_settings.inventory_checker is iterable

- name: Template >> /var/www/html/report/inventory_checker/groups.html
  template:
    src: "inventory_checker_groups.html.j2"
    dest: /var/www/html/report/inventory_checker/groups.html
    owner: root
    group: root
    mode: 0644
  tags:
    - templates
  when:
    - report_settings.inventory_checker is defined
    - report_settings.inventory_checker is not none
    - report_settings.inventory_checker
    - report_settings.inventory_checker is iterable
    - "'groups' in report_settings.inventory_checker"

- name: Template >> /var/www/html/report/inventory_checker/hosts.html
  template:
    src: "inventory_checker_hosts.html.j2"
    dest: /var/www/html/report/inventory_checker/hosts.html
    owner: root
    group: root
    mode: 0644
  tags:
    - templates
  when:
    - report_settings.inventory_checker is defined
    - report_settings.inventory_checker is not none
    - report_settings.inventory_checker
    - report_settings.inventory_checker is iterable
    - "'hosts' in report_settings.inventory_checker"

- name: Create report directories structure
  file:
   path: "{{item}}"
   state: directory
   mode: 0755
  with_items:
   - /dev/shm/ansible-cmdb/

- name: Gather all facts
  shell: ansible -m setup --tree /dev/shm/ansible-cmdb/ all
  ignore_errors: yes
  when: report_settings.enable_ansible_cmdb == true

- name: Generate facts report
  shell: ansible-cmdb /dev/shm/ansible-cmdb > /var/www/html/report/overview.html
  when: report_settings.enable_ansible_cmdb == true

- name: Generate graph-tool network report
  template:
    src: "graph-tool.py.j2"
    dest: /var/www/html/report/graphs/graph-tool.py
    owner: root
    group: root
    mode: 0644
  tags:
    - templates
    - graphtool
  when: report_settings.enable_graphtool == true

- name: Template >> /var/www/html/report/graphs_report.html
  template:
    src: "graphs_report.html.j2"
    dest: /var/www/html/report/graphs_report.html
    owner: root
    group: root
    mode: 0644
  tags:
    - templates
  when: report_settings.enable_graphtool == true

