---

- name: Restart pxe services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  loop: "{{ services_to_start[(ansible_distribution|lower|replace(' ','_'))]['_'+ansible_distribution_major_version] }}"
  tags:
    - service
