equipment_profile:

  access_control: true
  firewall: true

  operating_system:
    distribution: ubuntu
    distribution_major_version: 18
    distribution_version: 18.04

  equipment_type: server

  configuration:
    keyboard_layout: fr
    system_language: en_US.UTF-8

  hardware:
    cpu:
      architecture: arm64
      cores: 4

