---

- name: Package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rdma-core
    - libibverbs
    - libibverbs-devel
    - libibumad
    - infiniband-diags

- name: Enable/disable services
  service:
    name: rdma
    enabled: "{{ (enable_services | bool) | ternary('yes','no') }}"
  tags:
    - service

- name: Start services
  service:
    name: rdma
    state: started
  when: (start_services | bool)
  tags:
    - service
