---

- name: package █ Install infiniband minimal packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - rdma-core
    - libibverbs
    - libibverbs-devel
    - libibumad
    - infiniband-diags

- name: service █ Manage rdma state
  service:
    name: rdma
    enabled: yes
    state: started
  tags:
    - service
