---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansiblectrl
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: "/lib/systemd/systemd"
    capabilities:
      - "SYS_ADMIN"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      ansiblectrl:
        network_interfaces:
          en0:
            ip4: 10.10.0.1
verifier:
  name: ansible
